# Generated by Django 4.2.6 on 2023-12-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APM_H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aboutme_header', models.TextField()),
            ],
            options={
                'verbose_name': 'Aboutme_header',
                'verbose_name_plural': 'AboutMe_header',
            },
        ),
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50)),
                ('Percent', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'competence',
                'verbose_name_plural': 'Competences',
            },
        ),
        migrations.CreateModel(
            name='Competences_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
            ],
            options={
                'verbose_name': 'competence_header',
                'verbose_name_plural': 'Competences_Headers',
            },
        ),
        migrations.CreateModel(
            name='Contact_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact_header',
                'verbose_name_plural': 'Contacts_Headers',
            },
        ),
        migrations.CreateModel(
            name='EXP_pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poste', models.CharField(max_length=50)),
                ('Year_debut', models.DateField()),
                ('Year_end', models.DateField()),
                ('Entreprise', models.CharField(max_length=50)),
                ('Location_ville', models.CharField(max_length=50)),
                ('Location_pays', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'EXP_pro',
                'verbose_name_plural': 'EXPs_Pro',
            },
        ),
        migrations.CreateModel(
            name='fact_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
            ],
            options={
                'verbose_name': 'fact_header',
                'verbose_name_plural': 'Facts_Headers',
            },
        ),
        migrations.CreateModel(
            name='formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diplome', models.CharField(max_length=50)),
                ('Year_debut', models.DateField()),
                ('Year_end', models.DateField()),
                ('University', models.CharField(max_length=50)),
                ('Location_ville', models.CharField(max_length=50)),
                ('Location_pays', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='formation_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
            ],
            options={
                'verbose_name': 'formation_header',
                'verbose_name_plural': 'Formation_Headers',
            },
        ),
        migrations.CreateModel(
            name='jesuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jesuis', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'jesuis',
                'verbose_name_plural': 'JeSuiS',
            },
        ),
        migrations.CreateModel(
            name='JustMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('Number', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=50)),
                ('Pays', models.CharField(max_length=50)),
                ('Age', models.PositiveIntegerField()),
                ('LastDiploma', models.CharField(max_length=50)),
                ('Mail', models.EmailField(max_length=254)),
                ('Linked', models.CharField(max_length=50)),
                ('Freelance', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'juste_moi',
                'verbose_name_plural': 'Juste_Moi',
            },
        ),
        migrations.CreateModel(
            name='mynameis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mynameis', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'MonNom',
                'verbose_name_plural': 'MesNoms',
            },
        ),
        migrations.CreateModel(
            name='Portfolio_categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categorie', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'portfolio_categorie',
                'verbose_name_plural': 'Portfolio_categories',
            },
        ),
        migrations.CreateModel(
            name='Portfolio_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
            ],
            options={
                'verbose_name': 'portfolio_header',
                'verbose_name_plural': 'Portfolio_headers',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50)),
                ('Percent', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Services_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
            ],
            options={
                'verbose_name': 'services_header',
                'verbose_name_plural': 'Services_Headers',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Poste', models.CharField(max_length=50)),
                ('Adire', models.TextField()),
                ('DatePub', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Testimonials_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
            ],
            options={
                'verbose_name': 'Testimonial_header',
                'verbose_name_plural': 'Testimonials_Headers',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Titre',
                'verbose_name_plural': 'Titres',
            },
        ),
        migrations.CreateModel(
            name='Title_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_header', models.TextField()),
            ],
            options={
                'verbose_name': 'header_titre',
                'verbose_name_plural': 'Header_Titres',
            },
        ),
        migrations.CreateModel(
            name='Portfolio_carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carte', models.ImageField(upload_to=None)),
                ('Description', models.TextField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendPortfolio.portfolio_categorie')),
            ],
            options={
                'verbose_name': 'portfolio_carte',
                'verbose_name_plural': 'Portfolio_cartes',
            },
        ),
    ]
