# Generated by Django 4.2.6 on 2023-12-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='University',
            field=models.CharField(max_length=100),
        ),
    ]
