# Generated by Django 4.2.6 on 2023-12-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0002_alter_formation_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='Diplome',
            field=models.CharField(max_length=100),
        ),
    ]
