# Generated by Django 4.2.6 on 2023-12-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0003_alter_formation_diplome'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp_pro',
            name='Description',
            field=models.TextField(default=None),
        ),
    ]
