# Generated by Django 4.2.6 on 2023-12-02 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0004_exp_pro_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='mypic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mypic', models.ImageField(upload_to=None)),
            ],
            options={
                'verbose_name': 'maphoto',
                'verbose_name_plural': 'MesPhotos',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carte', models.ImageField(upload_to=None)),
                ('Description', models.TextField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Service_categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categorie', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Service_categorie',
                'verbose_name_plural': 'Services_categories',
            },
        ),
        migrations.RenameModel(
            old_name='Services_header',
            new_name='Service_header',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterModelOptions(
            name='service_header',
            options={'verbose_name': 'service_header', 'verbose_name_plural': 'Services_Headers'},
        ),
        migrations.AddField(
            model_name='service',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendPortfolio.service_categorie'),
        ),
    ]
