# Generated by Django 4.2.6 on 2023-12-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0005_mypic_service_service_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Carte',
        ),
        migrations.AddField(
            model_name='service',
            name='Titre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='Description',
            field=models.TextField(default=None),
        ),
    ]
