# Generated by Django 4.2.6 on 2023-12-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0006_remove_service_carte_service_titre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_categorie',
            name='Categorie',
            field=models.CharField(max_length=30),
        ),
    ]
