# Generated by Django 4.2.6 on 2023-12-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0008_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_carte',
            name='DateProjet',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='portfolio_carte',
            name='Name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio_carte',
            name='Url',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio_carte',
            name='Carte',
            field=models.ImageField(default=None, upload_to=None),
        ),
    ]
