# Generated by Django 4.2.6 on 2023-12-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0009_portfolio_carte_dateprojet_portfolio_carte_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_carte',
            name='NomProjet',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
