# Generated by Django 4.2.6 on 2023-12-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0010_portfolio_carte_nomprojet'),
    ]

    operations = [
        migrations.CreateModel(
            name='mescomptes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('insta', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'MonCompte',
                'verbose_name_plural': 'mescomptes',
            },
        ),
    ]
