# Generated by Django 4.2.6 on 2023-12-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0011_mescomptes'),
    ]

    operations = [
        migrations.AddField(
            model_name='justme',
            name='me',
            field=models.ImageField(default=None, upload_to=None),
        ),
    ]
