# Generated by Django 4.2.6 on 2023-12-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0016_alter_portfolio_carte_carte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_carte',
            name='Carte',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
