# Generated by Django 4.2.6 on 2023-12-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0020_alter_portfolio_carte_carte'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypic',
            name='baniere',
            field=models.ImageField(default=None, upload_to='Backend\\media\\media_cdn'),
        ),
        migrations.AlterField(
            model_name='justme',
            name='me',
            field=models.ImageField(default=None, upload_to='Backend\\media\\media_cdn'),
        ),
        migrations.AlterField(
            model_name='mypic',
            name='mypic',
            field=models.ImageField(upload_to='Backend\\media\\media_cdn'),
        ),
    ]
