# Generated by Django 4.2.6 on 2023-12-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0021_mypic_baniere_alter_justme_me_alter_mypic_mypic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypic',
            name='icon',
            field=models.ImageField(default=None, upload_to='Backend\\media\\media_cdn'),
        ),
    ]
