# Generated by Django 4.2.6 on 2023-12-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0022_mypic_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jesuis',
            name='jesuis',
        ),
        migrations.AddField(
            model_name='jesuis',
            name='jesuis1',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='jesuis',
            name='jesuis2',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='jesuis',
            name='jesuis3',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='jesuis',
            name='jesuis4',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
