# Generated by Django 4.2.6 on 2023-12-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0023_remove_jesuis_jesuis_jesuis_jesuis1_jesuis_jesuis2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='justme',
            name='LastDiploma_pic',
            field=models.ImageField(default=None, upload_to='Backend\\media\\media_cdn'),
        ),
    ]
