# Generated by Django 4.2.6 on 2023-12-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0026_remove_mypic_baniere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justme',
            name='LastDiploma_pic',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='justme',
            name='me',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mypic',
            name='icon',
            field=models.ImageField(default=None, upload_to='\\media\\media_cdn'),
        ),
        migrations.AlterField(
            model_name='mypic',
            name='mypic',
            field=models.ImageField(upload_to='\\media\\media_cdn'),
        ),
    ]
