# Generated by Django 4.2.6 on 2023-12-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0027_alter_justme_lastdiploma_pic_alter_justme_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypic',
            name='baniere',
            field=models.ImageField(default=None, upload_to='Backend\\media\\media_cdn'),
        ),
        migrations.AlterField(
            model_name='justme',
            name='LastDiploma_pic',
            field=models.ImageField(default=None, upload_to='Backend\\media\\media_cdn'),
        ),
        migrations.AlterField(
            model_name='justme',
            name='me',
            field=models.ImageField(default=None, upload_to='Backend\\media\\media_cdn'),
        ),
        migrations.AlterField(
            model_name='mypic',
            name='icon',
            field=models.ImageField(default=None, upload_to='Backend\\media\\media_cdn'),
        ),
        migrations.AlterField(
            model_name='mypic',
            name='mypic',
            field=models.ImageField(upload_to='Backend\\media\\media_cdn'),
        ),
    ]
