# Generated by Django 4.2.6 on 2023-12-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0028_mypic_baniere_alter_justme_lastdiploma_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypic',
            name='baniere',
        ),
    ]
