# Generated by Django 4.2.6 on 2023-12-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0030_testimonials_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='Mail',
            field=models.EmailField(max_length=254),
        ),
    ]
