# Generated by Django 4.2.6 on 2023-12-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0031_alter_testimonials_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='DatePub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
