# Generated by Django 4.2.6 on 2023-12-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0033_rename_visite_fact_projet_fact_collab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={'verbose_name': 'fact', 'verbose_name_plural': 'Facts'},
        ),
    ]
