# Generated by Django 4.2.6 on 2023-12-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0034_alter_fact_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fact',
        ),
    ]
