# Generated by Django 4.2.6 on 2023-12-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0035_delete_fact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fact_header',
        ),
    ]
