# Generated by Django 4.2.6 on 2023-12-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0036_delete_fact_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypic',
            name='icon',
        ),
    ]
