# Generated by Django 4.2.6 on 2024-01-18 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0040_alter_exp_pro_year_end_alter_formation_year_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justme',
            name='me',
        ),
    ]
