# Generated by Django 4.2.6 on 2024-01-18 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0041_remove_justme_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justme',
            name='LastDiploma_pic',
        ),
    ]
