# Generated by Django 4.2.6 on 2024-01-18 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0043_remove_portfolio_carte_carte_suplementaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_ajout_photo',
            name='NomProjet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendPortfolio.portfolio_carte'),
        ),
    ]
