# Generated by Django 4.2.6 on 2024-01-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0044_alter_portfolio_ajout_photo_nomprojet'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_carte',
            name='Carte_suplementaire',
            field=models.ImageField(blank=True, default=None, upload_to='Backend\\media\\media_cdn'),
        ),
        migrations.DeleteModel(
            name='portfolio_ajout_photo',
        ),
    ]
