# Generated by Django 4.2.6 on 2024-05-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0045_portfolio_carte_carte_suplementaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_carte',
            name='Carte_suplementaire',
            field=models.ImageField(default=None, upload_to='Backend\\media\\media_cdn'),
        ),
    ]
