# Generated by Django 4.2.6 on 2024-05-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0046_alter_portfolio_carte_carte_suplementaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_carte',
            name='DateProjet',
            field=models.DateField(auto_now_add=True),
        ),
    ]
