# Generated by Django 4.2.6 on 2024-06-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0047_alter_portfolio_carte_dateprojet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypic',
            name='mypic',
            field=models.ImageField(upload_to='Projet_Wah\\media\\media_cdn'),
        ),
    ]
