# Generated by Django 4.2.6 on 2024-06-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendPortfolio', '0048_alter_mypic_mypic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='Year_end',
            field=models.DateField(default=None),
        ),
    ]
